INFO     [2024-09-27 15:53:17,116] [none] django.utils.autoreload: Watching for file changes with StatReloader
ERROR    [2024-09-27 15:54:47,955] [de69c01dbb4e4352bd34d972a903bb65] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-09-27 15:54:47,979] [067f8765079e4badabfea2914fc35c00] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-09-27 15:54:48,069] [de69c01dbb4e4352bd34d972a903bb65] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
INFO     [2024-09-27 15:55:45,605] [none] django.utils.autoreload: Watching for file changes with StatReloader
ERROR    [2024-09-27 16:58:08,361] [2687d50bb88b479b8e9737e6e8dff794] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-09-27 16:58:08,390] [6ad61325756346a7a44283724c25600c] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-09-27 16:58:08,421] [2687d50bb88b479b8e9737e6e8dff794] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
INFO     [2024-09-27 16:59:57,309] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-09-27 16:59:58,515] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-09-29 14:42:37,772] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\routers\case.py changed, reloading.
INFO     [2024-09-29 14:42:39,124] [none] django.utils.autoreload: Watching for file changes with StatReloader
ERROR    [2024-09-29 15:18:17,826] [aba82b8641c3444295c3e888bc1ebfba] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-09-29 15:18:17,834] [0c4b19f89e4e4f638d82f1f33f636370] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-09-29 15:18:17,870] [aba82b8641c3444295c3e888bc1ebfba] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
ERROR    [2024-09-29 15:21:09,671] [ab57d2e8b2084a0ea66dd99d4d2d853a] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-09-29 15:21:09,690] [bb7df0740a0e4edcb213e12285c041bd] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-09-29 15:21:09,702] [ab57d2e8b2084a0ea66dd99d4d2d853a] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
INFO     [2024-09-30 10:53:47,869] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\models\https.py changed, reloading.
INFO     [2024-09-30 10:53:49,728] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-09-30 13:30:39,210] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\routers\case.py changed, reloading.
INFO     [2024-09-30 13:30:40,623] [none] django.utils.autoreload: Watching for file changes with StatReloader
ERROR    [2024-10-10 17:41:04,388] [424153126a674a988fab7d52dce3bfa4] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-10-10 17:41:04,432] [ec1aad4dd4414e6abdfbe549bd53bdba] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-10-10 17:41:04,471] [424153126a674a988fab7d52dce3bfa4] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
ERROR    [2024-10-10 17:41:07,725] [61d0d7e9955b4bd19d7c5f03f378be85] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-10-10 17:41:07,747] [120fa97843e84b7b8001f5631a675238] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-10-10 17:41:07,768] [61d0d7e9955b4bd19d7c5f03f378be85] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
ERROR    [2024-10-10 17:41:14,554] [a74866e59e434c3ca5b244e224b987c2] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-10-10 17:41:14,578] [87bab061eb904b3cb24b84c81ed10d97] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-10-10 17:41:14,597] [a74866e59e434c3ca5b244e224b987c2] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
ERROR    [2024-10-10 17:41:56,391] [f3896f34b0914ab1b92a165bffb64b05] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-10-10 17:41:56,422] [f3896f34b0914ab1b92a165bffb64b05] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
ERROR    [2024-10-10 17:42:19,688] [e3dcf34fd9744ec09e638d7c28e601bc] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-10-10 17:42:19,709] [9dfe91c0618a448ca0b2c80bea9e015d] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-10-10 17:42:19,729] [e3dcf34fd9744ec09e638d7c28e601bc] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
INFO     [2024-10-10 17:47:00,222] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-10 17:47:01,758] [none] django.utils.autoreload: Watching for file changes with StatReloader
ERROR    [2024-10-11 10:00:28,800] [4625b5982912419e9783c642c8269d86] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-10-11 10:00:28,967] [4625b5982912419e9783c642c8269d86] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
INFO     [2024-10-14 16:49:33,457] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-14 17:35:54,200] [none] django.utils.autoreload: Watching for file changes with StatReloader
ERROR    [2024-10-14 18:26:56,495] [0b68167153554e9ab4f0f577bd65cb9f] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-10-14 18:26:56,512] [1ec1d92c4b8d42cdb135bb315987041a] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-10-14 18:26:56,528] [0b68167153554e9ab4f0f577bd65cb9f] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
ERROR    [2024-10-17 15:58:44,794] [bd485613bea44e8285adeb4aa42a5d95] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-10-17 15:58:44,810] [1ddcc8c45de04165a3ff04729bdfd52c] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-10-17 15:58:44,822] [bd485613bea44e8285adeb4aa42a5d95] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
INFO     [2024-10-18 13:49:37,361] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\emus\__init__.py changed, reloading.
INFO     [2024-10-18 13:49:37,756] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\emus\__init__.py changed, reloading.
INFO     [2024-10-18 13:49:39,160] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-18 13:49:39,199] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:12:10,984] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\emus\__init__.py changed, reloading.
INFO     [2024-10-31 15:12:14,819] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:30:33,834] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\views\https.py changed, reloading.
INFO     [2024-10-31 15:30:35,133] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:31:01,947] [none] django.utils.autoreload: Watching for file changes with StatReloader
WARNING  [2024-10-31 15:49:26,313] [b59d93b7a3c5470aad370bd0397faff7] django.request: Not Found: /api/http/step/saveOrUpdate/17
WARNING  [2024-10-31 15:49:29,073] [8460b9f3942845368629b46b90eaaa1a] django.request: Not Found: /api/http/step/saveOrUpdate/17
INFO     [2024-10-31 15:51:15,173] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\routers\case.py changed, reloading.
INFO     [2024-10-31 15:51:15,905] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\routers\case.py changed, reloading.
INFO     [2024-10-31 15:51:16,460] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:51:17,191] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:52:12,249] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\routers\case.py changed, reloading.
INFO     [2024-10-31 15:52:13,091] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\routers\case.py changed, reloading.
INFO     [2024-10-31 15:52:13,561] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:52:14,267] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:54:00,337] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:54:01,052] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:54:01,958] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:54:02,517] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:54:10,929] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:54:11,648] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:54:12,380] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:54:12,924] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:54:15,396] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:55:25,762] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:55:26,519] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:55:27,034] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:55:27,822] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:55:29,151] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:56:16,726] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:56:16,961] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:56:17,364] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:56:18,674] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:56:20,111] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:57:37,235] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:57:37,683] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:57:38,528] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:57:38,939] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:58:05,888] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:58:06,330] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 15:58:07,183] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:58:07,592] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 15:58:11,560] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:01:02,432] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:01:03,774] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:01:04,297] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:01:45,061] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:01:46,578] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:01:46,977] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:04:16,140] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:04:16,270] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:04:17,495] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:04:19,986] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:04:55,787] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:04:56,159] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:04:57,084] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:04:57,422] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:07:21,225] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:07:22,682] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:07:23,237] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:08:31,797] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:08:33,263] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:08:33,731] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:09:28,889] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:09:28,948] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:09:30,264] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:09:30,287] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:10:16,579] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:10:17,567] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:10:17,954] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:10:18,804] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:10:56,402] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:10:57,705] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:10:59,341] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:11:01,884] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:11:22,422] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:11:23,617] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:11:24,367] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:12:09,557] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:12:09,608] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:12:10,745] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:12:10,809] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:13:30,636] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:13:31,087] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:13:31,945] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:13:32,338] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:15:06,919] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:15:07,295] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:15:08,265] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:15:08,608] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:16:14,061] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:16:14,219] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:16:15,332] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:16:15,470] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:22:23,520] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:22:23,904] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:22:24,809] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:22:25,186] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:24:31,535] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 16:24:32,984] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 16:24:33,531] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:38:00,261] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\views\https.py changed, reloading.
INFO     [2024-10-31 17:38:01,714] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:38:01,935] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:42:21,367] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:42:21,399] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:42:22,798] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:42:22,824] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:43:01,777] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:43:01,969] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:43:03,094] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:43:03,270] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:43:34,188] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:43:34,899] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:43:35,420] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:43:36,178] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:44:06,296] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:44:07,584] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:44:07,919] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:44:25,662] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:44:26,801] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:44:28,649] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:45:05,012] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:46:08,889] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:46:09,285] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:46:10,330] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:46:10,673] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:46:19,529] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:48:19,362] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:48:20,837] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:48:21,370] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:48:42,486] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:48:43,815] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:48:43,825] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:53:07,712] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:53:09,055] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:53:09,169] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:55:10,925] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:55:10,944] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:55:12,211] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:55:12,252] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:59:13,564] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 17:59:15,039] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 17:59:15,551] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:01:00,188] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:01:00,207] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:01:01,568] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:01:03,869] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:01:49,843] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:01:51,312] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:01:51,820] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:02:39,899] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:02:41,268] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:02:43,812] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:03:53,025] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:03:54,487] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:03:55,052] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:04:10,448] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:04:11,770] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:04:12,138] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:06:00,239] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:06:00,550] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:06:01,575] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:06:01,773] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:06:14,360] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:06:14,452] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:06:15,724] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:06:17,361] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:07:20,192] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:07:20,281] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:07:21,485] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:07:21,568] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:07:23,977] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:09:24,453] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:09:24,771] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:09:25,793] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:09:26,108] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:11:21,482] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:11:21,506] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:11:22,805] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:11:22,832] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:14:16,044] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:14:16,078] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:14:17,395] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:14:17,402] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:17:15,907] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:17:15,916] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:17:17,330] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:17:17,351] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:17:48,141] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:17:48,299] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:17:49,528] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:17:49,753] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:20:24,339] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:21:00,090] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:21:01,575] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:21:01,928] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:22:44,330] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:22:45,781] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:22:45,924] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:23:49,218] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:23:50,453] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:23:50,509] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:25:25,638] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:25:26,956] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:25:27,032] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:25:41,787] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:25:42,863] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:25:42,998] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:26:19,149] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:26:20,333] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:26:20,387] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:27:00,875] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:27:01,749] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-10-31 18:27:02,219] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-10-31 18:27:03,118] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:03:31,533] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:03:32,889] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:03:33,265] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:04:28,135] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:04:29,381] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:04:29,381] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:05:31,824] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:05:33,338] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:05:33,840] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:06:01,177] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:06:02,483] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:06:03,191] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:07:10,324] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:07:11,738] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:07:11,812] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:07:33,339] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:07:34,742] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:07:35,327] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:07:49,488] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:07:49,608] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:07:50,959] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:07:51,028] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:08:42,687] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:08:43,708] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:08:43,851] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:12:01,532] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:12:02,718] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:12:02,809] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:14:07,421] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:14:08,075] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:14:08,728] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:14:09,363] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:14:25,793] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:14:27,015] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:14:27,206] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:14:49,049] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:14:49,700] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:14:50,367] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:14:50,939] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:15:12,650] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:15:13,215] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:15:13,993] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:15:14,478] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:15:52,195] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:15:52,238] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:15:53,491] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:15:53,546] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:16:47,467] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:16:48,922] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:16:49,341] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:17:15,017] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:17:15,128] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:17:16,430] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:17:16,495] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:17:58,590] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:17:59,033] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:17:59,903] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:18:00,303] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:18:51,174] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:18:52,402] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:18:52,691] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:20:53,121] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:20:54,304] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:20:54,377] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:21:50,903] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:21:51,244] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:21:52,171] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:21:52,497] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:26:12,953] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:26:13,371] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:26:14,200] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:26:14,552] [none] django.utils.autoreload: Watching for file changes with StatReloader
ERROR    [2024-11-01 10:30:50,868] [1eff172ab1c442cfa888e4505594d148] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-11-01 10:30:50,897] [4833fc0eeaef4c10b0d928515765652e] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-11-01 10:30:50,919] [1eff172ab1c442cfa888e4505594d148] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
ERROR    [2024-11-01 10:32:14,414] [1604caf900f94615b2c3459511d5ca2f] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-11-01 10:32:14,435] [328f157af0d74899a8b8a9c03377c116] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-11-01 10:32:14,452] [1604caf900f94615b2c3459511d5ca2f] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
INFO     [2024-11-01 10:39:31,842] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 10:39:33,210] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 10:39:33,691] [none] django.utils.autoreload: Watching for file changes with StatReloader
ERROR    [2024-11-01 11:15:41,669] [d0f393aed325410e9eba009fcfc63671] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-11-01 11:15:41,728] [a5015e5c623f44eabd6e2a31d9f3fc16] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-11-01 11:15:41,780] [d0f393aed325410e9eba009fcfc63671] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
ERROR    [2024-11-01 11:18:56,030] [222d452e605d4f05afb645094dee8bd9] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-11-01 11:18:56,048] [8787fae0c7fa4aa0bbfee6592eb82e31] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-11-01 11:18:56,061] [222d452e605d4f05afb645094dee8bd9] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
ERROR    [2024-11-01 11:28:05,920] [903e85c1d4474849a723ac2166fe56ec] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-11-01 11:28:05,954] [903e85c1d4474849a723ac2166fe56ec] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
WARNING  [2024-11-01 11:28:05,962] [163812a6903f4b36a1ee6f26ad1e4e66] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
ERROR    [2024-11-01 11:28:16,694] [1b05d0e17ac04aecaf5b80f1751823e3] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-11-01 11:28:16,699] [fec6e9302ef84c18b7874df97585c457] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-11-01 11:28:16,726] [1b05d0e17ac04aecaf5b80f1751823e3] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
ERROR    [2024-11-01 11:28:21,369] [3303b4927c2046c5b52ca469fa570e7e] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-11-01 11:28:21,407] [5a19c500c6d849a4b0c6889a588311a9] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-11-01 11:28:21,410] [3303b4927c2046c5b52ca469fa570e7e] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
INFO     [2024-11-01 13:51:41,774] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 13:51:42,098] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 13:51:43,539] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 13:51:43,539] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 13:55:00,734] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 13:55:01,943] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 13:56:29,008] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 13:56:30,130] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 13:56:30,403] [none] django.utils.autoreload: Watching for file changes with StatReloader
WARNING  [2024-11-01 13:58:32,351] [8dce0e567d5349b792089d229f5e2b53] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
INFO     [2024-11-01 13:58:53,345] [none] django.utils.autoreload: Watching for file changes with StatReloader
WARNING  [2024-11-01 13:59:07,745] [53be1ac6e8b94f6fb15b2b873660ea41] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 13:59:13,133] [0909fe710b904b839b05c4e921e69e35] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
INFO     [2024-11-01 14:01:08,519] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 14:01:10,652] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:01:11,892] [none] django.utils.autoreload: Watching for file changes with StatReloader
WARNING  [2024-11-01 14:01:20,481] [9359f1d8dc0e40c98c72d4f81d15a801] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:01:25,757] [32d4e8def4b84b40b6c5237291e02089] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:07,129] [5a2a9e1c958a4afb92efcaa105699c2e] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:12,092] [9d683b4f30df4157b5d2f7b51d273c97] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:12,818] [9831b758eba34f0d9f39781602c0d941] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:13,286] [8a2c50de06654f7096359d46c697f0f1] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:13,506] [0a951290d56444c3abdd9c3347f45ebd] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:13,643] [15243289bb06422082d8715d3056de28] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:13,813] [48d7fc121318457c8ff065c3a217495e] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:13,979] [56b64a9327014f2c8da926fa5f36c613] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:14,145] [0d70d2821c01496ca1cba2584ae955d1] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:14,323] [d191655eb74244ec92685aa420afbcc4] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:14,497] [e2746f95cfc947fab3b4bdd6c81e7d6f] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:14,689] [17559d55ddf648c69068a0472379e702] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:14,857] [129838d6aef64bab964a9e5a43eb6457] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:15,030] [90d14065529549c998e01382cb78194e] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:15,191] [4e98cd05ed8e494fa996f0a85b8dcc20] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 14:04:15,409] [d31054d879ae4058b66ffa43eab17430] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
INFO     [2024-11-01 14:06:11,965] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:06:12,146] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:06:13,578] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:06:13,662] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:06:50,534] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:06:50,784] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:06:52,312] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:06:52,415] [none] django.utils.autoreload: Watching for file changes with StatReloader
WARNING  [2024-11-01 14:07:19,364] [dce09551d02e4a83b07908e5b253bd75] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
INFO     [2024-11-01 14:11:28,162] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:11:28,680] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:11:29,464] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:11:29,977] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:12:23,640] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:12:23,795] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:12:25,928] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:12:26,060] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:13:51,912] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:13:54,388] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:13:55,614] [none] django.utils.autoreload: Watching for file changes with StatReloader
WARNING  [2024-11-01 14:14:14,036] [8582a0e9245644f48e2a8694f0a88d95] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
ERROR    [2024-11-01 14:20:00,323] [1d6682a58d8342ec8ea995fb86fcbe36] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-11-01 14:20:00,335] [5350be1a94db419e99b46bca166b18ad] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-11-01 14:20:00,346] [1d6682a58d8342ec8ea995fb86fcbe36] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
INFO     [2024-11-01 14:21:26,186] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:21:26,289] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:21:28,216] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:21:28,328] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:21:33,724] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\scheduler\scheduler.py changed, reloading.
INFO     [2024-11-01 14:21:34,810] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:21:34,939] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:22:33,705] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:23:29,433] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:23:48,306] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:26:07,917] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 14:26:09,736] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:26:21,585] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 14:26:23,046] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:27:18,998] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\https.py changed, reloading.
INFO     [2024-11-01 14:27:20,162] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:27:40,693] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:30:10,262] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:36:49,474] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\services\protos\executor_pb2_grpc.py changed, reloading.
INFO     [2024-11-01 14:36:51,112] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:37:06,668] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\services\executor.py changed, reloading.
INFO     [2024-11-01 14:37:08,373] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:38:10,287] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\services\executor.py changed, reloading.
INFO     [2024-11-01 14:38:11,957] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:38:48,998] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:39:16,950] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:42:14,651] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:45:02,806] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:47:27,041] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:49:44,540] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:50:37,236] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:51:46,598] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 14:53:51,943] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 15:35:59,318] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 15:37:04,533] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 16:43:51,820] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 16:44:37,689] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 16:49:44,904] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 16:50:36,210] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 16:50:59,750] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 16:53:02,238] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 16:58:02,002] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 16:58:50,315] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 16:59:02,044] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 16:59:47,092] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 17:05:06,772] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 17:05:25,878] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 17:09:54,226] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 17:11:58,372] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 17:13:41,734] [none] django.utils.autoreload: Watching for file changes with StatReloader
WARNING  [2024-11-01 17:30:59,414] [355d0d3015da4cf787bedef9e6241557] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 17:31:00,894] [060be4e8926344bcaf04560cdc041450] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 17:31:02,863] [22452aa20f864dcb8e0e1ec71b5f1e08] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 17:31:03,037] [a718d74577664853adc3c0cdfd797830] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
WARNING  [2024-11-01 17:31:03,227] [96294050aed64981b013e586b80cbb9f] django.request: Not Found: /api/plan/SaveOrUpdate/undefined
INFO     [2024-11-01 17:58:08,125] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 18:03:31,054] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\unitrunner\request\http.py changed, reloading.
INFO     [2024-11-01 18:03:32,868] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 18:09:09,617] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\dashboard.py changed, reloading.
INFO     [2024-11-01 18:09:10,936] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 18:14:27,262] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\response\fatcory.py changed, reloading.
INFO     [2024-11-01 18:14:28,842] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 18:16:35,952] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\dao\dashboard.py changed, reloading.
INFO     [2024-11-01 18:16:37,122] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-01 18:27:39,955] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\services\executor.py changed, reloading.
INFO     [2024-11-01 18:27:41,239] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-04 13:36:29,516] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-04 13:36:59,311] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-04 13:37:43,413] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-04 13:37:55,263] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-04 13:42:43,295] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\views\https.py changed, reloading.
INFO     [2024-11-04 13:42:43,544] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\api\views\https.py changed, reloading.
INFO     [2024-11-04 13:42:44,777] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-04 13:42:45,039] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-04 13:59:13,437] [none] django.utils.autoreload: C:\Users\86135\Desktop\EasyPost\unit-backend\common\process\parser.py changed, reloading.
INFO     [2024-11-04 13:59:14,854] [none] django.utils.autoreload: Watching for file changes with StatReloader
INFO     [2024-11-04 13:59:14,854] [none] django.utils.autoreload: Watching for file changes with StatReloader
ERROR    [2024-11-04 13:59:29,435] [c640f2a33b3e4704851b21cbdbecca93] django.security.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
Traceback (most recent call last):
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\static.py", line 45, in serve
    fullpath = Path(safe_join(document_root, path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86135\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\_os.py", line 31, in safe_join
    raise SuspiciousFileOperation(
django.core.exceptions.SuspiciousFileOperation: The joined path (C:\Users\86135\Desktop\EasyPost\backend\api\templates\media\default.png) is located outside of the base path component (C:\Users\86135\Desktop\EasyPost\unit-backend\api\templates\media)
WARNING  [2024-11-04 13:59:29,456] [f1a7c60528fa4ce6ba9db3b5276367b5] django.request: Not Found: /media/C:/Users/86135/Desktop/EasyPost/unit-backend/api/templates/media/default.png
WARNING  [2024-11-04 13:59:29,480] [c640f2a33b3e4704851b21cbdbecca93] django.request: Bad Request: /media/C:/Users/86135/Desktop/EasyPost/backend/api/templates/media/default.png
INFO     [2024-11-04 14:19:41,323] [none] django.utils.autoreload: Watching for file changes with StatReloader
